default: &default
adapter: postgresql
encoding: utf8
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
username: root
password:
socket: /tmp/mysql.sock


development:
<<: *default
database: protospace_40084_development


test:
<<: *default
database: protospace_40084_test


production:
<<: *default
database: protospace_40084_production
username: protospace_40084
password: <%= ENV["PROTOSPACE_40084_DATABASE_PASSWORD"] %>